asr_model:
  optimizer_opt:
    k: 1.0
    warmup_steps: 4000

  encoder:
    idim: 83
    d_model: 512
    nhead: 8
    nlayers: 2
    d_inner: 2048
    dropout: 0.1

  decoder:
    d_model: 512
    nhead: 8
    nlayers: 4
    d_inner: 2048
    dropout: 0.1

solver:
  # Data options
  setting: 'mono-transformer-test' # seems no need to add baseline or something
  data_root: 'data'
  total_epochs: 2
  spm_mapping: 'data/valid_train_en_unigram150_units.txt'
  spm_model: 'data/valid_train_en_unigram150.model'
  label_smoothing: 0.1
  #total_epochs: 25

  # Validation options
  #eval_ival: 20
  eval_ival: 10000
  log_ival: 10

  batch_size: 32 
  dev_batch_size: 32
  min_ilen: 10
  max_ilen: 3000
  dev_max_ilen: 3000
  half_batch_ilen: 512

  beam_decode:
    min_step_ratio: 0.0
    max_step_ratio: 1.0
    beam_size: 20
    att_w: 0.5
    ctc_w: 0.5
    lm_w: 0
